import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { HeroHeading } from "@/components/design/headings/HeroHeading";
import Image from "next/image";
import Sidebar from "@/components/layout/sidebar";
import Breadcrumb from "@/components/layout/Breadcrumb";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>
            <div className="flex justify-start flex-col items-center bg-white h-screen">
                <section className="pt-16 lg:pt-26 pb-10">
                <HeroHeading className="flex items-center justify-center gap-4">
                    <Image src="/client_garage.png" height={100} alt="Logo" width={100}/>
                    Client Garage - Dashboard
                </HeroHeading>

                </section>
                <section className="flex flex-row justify-center gap-14 w-full h-[425px] px-10 w-full">
                    <Sidebar/>
                    <div className="flex flex-col">
                        <Breadcrumb/> 
                        {children}
                    </div>
                </section>
            </div>
        </main>
      </body>
    </html>
  );
}
